### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by huajideshutiao** [Xposed-Modules-Repo/Hook.JiuWu.Xp#1]
虽然秦心真的很好看，但是能不能开屏只显示一次。
还有能不能加个米游社去开屏广告😋

**Comment by lovejiuwu** [comment]
第一个想法我不赞同
第二个米游社又是什么东西

**Comment by huajideshutiao** [comment]
米游社的实现[这里](https://github.com/hujiayucc/Fuck-AD) 有

**Comment by lovejiuwu** [comment]
好的 我看了下确实有
原理也很简单
com.mihoyo.hyperion.ui.SplashActivity onCreate
执行后跳转到主页即可
val activity = instance<Activity>()
                    val context = activity.applicationContext
                    val intent = Intent(context,"com.mihoyo.hyperion.main.HyperionMainActivity".toClass())
                    intent.flags = Intent.FLAG_ACTIVITY_NEW_TASK
                    context.startActivity(intent)
                    activity.finish()

你是否有添加tg群组

**Comment by huajideshutiao** [comment]
tg群加了啊

**Comment by maoli531** [comment]
快连 2.18.18 破解不了了，一直是 60 分钟免费体验

**Comment by lovejiuwu** [comment]
降级337版本



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月27日(周三) 晚上10:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Xposed-Modules-Repo/Hook.JiuWu.Xp] 一些建议 (Issue #1)




 
快连 2.18.18 破解不了了，一直是 60 分钟免费体验

**Comment by maoli531** [comment]
感谢，降级后正常使用

**Comment by maoli531** [comment]
![Screenshot_2023-10-04-22-24-27-39_084ab3bc34f7aa7ccff83653f52abafc.png](https://github.com/Xposed-Modules-Repo/Hook.JiuWu.Xp/assets/18110406/b23644f4-0a12-48e6-8938-d7f391c9a3af)

**Comment by lovejiuwu** [comment]
提供lsp日志



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月4日(周三) 晚上10:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Xposed-Modules-Repo/Hook.JiuWu.Xp] 一些建议 (Issue #1)




  
快连 2.18.18 破解不了了，一直是 60 分钟免费体验
  
3.4.0 又不行了

**Comment by huajideshutiao** [comment]
> > 快连 2.18.18 破解不了了，一直是 60 分钟免费体验
> 
> 3.4.0 又不行了![Screenshot_2023-10-04-22-23-47-43_b925948ebc6526d76511b6ea3af63aeb.png](https://user-images.githubusercontent.com/18110406/272608795-1048a5cf-22d6-4bd1-b4ff-c0dbe6d3b958.png)

别在我这回复，单开一个issue去

**Comment by maoli531** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月4日(周三) 晚上10:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Xposed-Modules-Repo/Hook.JiuWu.Xp] 一些建议 (Issue #1)




 提供lsp日志 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2023年10月4日(周三) 晚上10:30 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [Xposed-Modules-Repo/Hook.JiuWu.Xp] 一些建议 (Issue #1) 
 
 
 
 
    
 快连 2.18.18 破解不了了，一直是 60 分钟免费体验 
    
 3.4.0 又不行了
