### ISSUE TITLE
hookvip 一木记账失效，降级也失效，猜测作者更换接口

### ISSUE THREAD

**Issue by mcxiaochenn** [Xposed-Modules-Repo/Hook.JiuWu.Xp#25]
hookvip 一木记账失效，降级也失效，猜测作者更换接口
![Screenshot_2024-05-22-02-03-42-908_com eg android AlipayGphone](https://github.com/Xposed-Modules-Repo/Hook.JiuWu.Xp/assets/130777336/e2d34871-077b-4e0f-87fb-cbca5e00cea2)
![Screenshot_2024-05-22-02-12-08-262_com wangc bill](https://github.com/Xposed-Modules-Repo/Hook.JiuWu.Xp/assets/130777336/1fbf46c7-c699-4f89-974f-5fd29960cc50)
![Screenshot_2024-05-22-02-12-11-703_com wangc bill](https://github.com/Xposed-Modules-Repo/Hook.JiuWu.Xp/assets/130777336/a6e1fb83-f15e-4c11-bf92-d9ed87374435)

**Comment by mcxiaochenn** [comment]
降级指的是一木记账降级，刚刚hookvip降级到3.5.4（fix）发现功能正常，3.5.5有问题啊，要不在更一个3.5.5（fix）？应该不是我包的问题，123下的

**Comment by dulinxi** [comment]
3.5.5无法使用，重新安装3.5.4正常

**Comment by mcxiaochenn** [comment]
已降级3.5.4，确定是3.5.5的问题了，坐等开发者更新
